// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDq4NXxkKdRFmvXpEOD80Vzj04phVEfwdU',
    appId: '1:186352700746:web:d0b86b8de69ce5e48985b3',
    messagingSenderId: '186352700746',
    projectId: 'gen-lang-client-0541040108',
    authDomain: 'gen-lang-client-0541040108.firebaseapp.com',
    storageBucket: 'gen-lang-client-0541040108.firebasestorage.app',
    measurementId: 'G-TT2W8W6GTV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGUPGCjuZoUlKdyMEPPSHP4IpbOglzX08',
    appId: '1:186352700746:android:e14850d01f96cf718985b3',
    messagingSenderId: '186352700746',
    projectId: 'gen-lang-client-0541040108',
    storageBucket: 'gen-lang-client-0541040108.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdiN67CODPCDuxDTGJwdSk_d9J3q8cOew',
    appId: '1:186352700746:ios:271fd6db993424ca8985b3',
    messagingSenderId: '186352700746',
    projectId: 'gen-lang-client-0541040108',
    storageBucket: 'gen-lang-client-0541040108.firebasestorage.app',
    androidClientId: '186352700746-29lsg2jejh64ud5hds26tjeh50u1ee2o.apps.googleusercontent.com',
    iosBundleId: 'com.bryloq.app',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdiN67CODPCDuxDTGJwdSk_d9J3q8cOew',
    appId: '1:186352700746:ios:6babf7609e9a03bb8985b3',
    messagingSenderId: '186352700746',
    projectId: 'gen-lang-client-0541040108',
    storageBucket: 'gen-lang-client-0541040108.firebasestorage.app',
    androidClientId: '186352700746-chlq186nf6vlhoifd72vk186bcvvmk17.apps.googleusercontent.com',
    iosBundleId: 'com.example.saydoAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDq4NXxkKdRFmvXpEOD80Vzj04phVEfwdU',
    appId: '1:186352700746:web:eddab406c2d2aca78985b3',
    messagingSenderId: '186352700746',
    projectId: 'gen-lang-client-0541040108',
    authDomain: 'gen-lang-client-0541040108.firebaseapp.com',
    storageBucket: 'gen-lang-client-0541040108.firebasestorage.app',
    measurementId: 'G-F4558ZVB1F',
  );
}
